global:
  resolve_timeout: 5m
  # Placeholder for a real SMTP server configuration
  smtp_from: 'alertmanager@example.com'
  smtp_smarthost: 'localhost:1025' # This would be a real server e.g., smtp.gmail.com:587
  smtp_require_tls: false

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'admin@wearipedia.com'
    send_resolved: true